### ISSUE TITLE
Playervyn innehållet floatas fel (desktop)

### ISSUE THREAD

**Issue by fh222dt** [rn222cx/1DV411_Grupp3#146]
Most contributing & explore topics hamnar under spelaren, floatat helt till vänster. Stänger man av floaten så lägger sig innehållet på sidan av spelaren som det ska vara. 

Detta uppstår bara på live-servern, ej lokalt

**Comment by AndreasAnemyrLNU** [comment]
fixar du detta själv. Ange gärna url och helst skärmdump också :)
