### ISSUE TITLE
Högermarginal stämmer inte på ipad

### ISSUE THREAD

**Issue by sj222mk** [rn222cx/1DV411_Grupp3#147]

**Comment by me222wm** [comment]
Samma på android: 

![screenshot_20160310-230927](https://cloud.githubusercontent.com/assets/8631192/13686364/a6c9c392-e715-11e5-9269-06247f69c5b9.png)

**Comment by sj222mk** [comment]
OBS samma på iPhone 6!

**Comment by AndreasAnemyrLNU** [comment]
Kolla detta igen efter att fh har bergat in från branch issue#148

**Comment by sj222mk** [comment]
Nu ser det bra ut! Har kollat även liggande och layouten fungerar där med!
