### ISSUE TITLE
Player svart bakgrund går inte hela vägen ut

### ISSUE THREAD

**Issue by me222wm** [rn222cx/1DV411_Grupp3#148]
![skarmklipp](https://cloud.githubusercontent.com/assets/8631192/13665625/b58b8766-e6ad-11e5-9205-3a6caec0ea88.PNG)

**Comment by AndreasAnemyrLNU** [comment]
påbörjad i branch iisue#148

någon verkade anget padding på en ipad no-padding class....
Återstår docl att lägga till en klass på unauthorized reset sidan.
Hittar den inte :-1: 

Lägger man till klass unauthorized-form i formelement så bör det stämma...

**Comment by me222wm** [comment]
Ser fint ut nu.

**Comment by AndreasAnemyrLNU** [comment]
Klart!
