### ISSUE TITLE
Bild när dela på facebook

### ISSUE THREAD

**Issue by mi222ep** [rn222cx/1DV411_Grupp3#158]
När länk delas på facebook visas ingen bild (men länken formateras som om det vore en bild). Lägga in logotypen eller liknande där?

**Comment by rn222cx** [comment]
Brukar inte dessa tjänster plocka bilderna från meta headern, ex
`<meta property="og:image" content="sökväg_till_bild.jpg"/>`

**Comment by AndreasAnemyrLNU** [comment]
Klart!
