### ISSUE TITLE
Om man raderar expert försvinner inte dennes podcasts

### ISSUE THREAD

**Issue by me222wm** [rn222cx/1DV411_Grupp3#160]
Om man tar bort en expert försvinner inte poddarna, vilket gör att applikationen krashar.

**Comment by AndreasAnemyrLNU** [comment]
Tänker att kan man verkligen radera en expert. Nånting säger mig att softdelete kanske kan påverka?

**Comment by me222wm** [comment]
Expert har ju det om jag har förstått saken rätt.

**Comment by rn222cx** [comment]
Pusha upp lösning på existerande issue#161 branchen för att minimera branches
