### ISSUE TITLE
Explore topics: visar ämnen som inte har någon expert. 

### ISSUE THREAD

**Issue by me222wm** [rn222cx/1DV411_Grupp3#162]
Borde inte dyka upp kategorier som inte har någon expert när man klickar på länk i dashboard. Får ibland bara upp en tom listai explorevyn.

**Comment by AndreasAnemyrLNU** [comment]
Kan du posta urlen för detta?

**Comment by AndreasAnemyrLNU** [comment]
som denna kanske :)
http://utbildning.fridaholmstrom.se/explore/management-business-growth

**Comment by me222wm** [comment]
Ja skulle just skicka den. :)

**Comment by AndreasAnemyrLNU** [comment]
Stänger denna då den verkar var ok efter egen testning...

**Comment by me222wm** [comment]
Problemet kravstår för mig.

**Comment by AndreasAnemyrLNU** [comment]
Fix fungerar för mig och mikael på lokal vagrant och senaste version av branch master.

@fh222dt kan det vara något strul med publicering av issue#162, den borde mergats i fredags eller lördags?

**Comment by AndreasAnemyrLNU** [comment]
@fh222dt 
Mikael har pusaht upp vad vi tror löser bugg för tomma topics.
Vore väldigt bra om du kunde merga in och publicera detta på servern så vi vet att det fungerar....
