### ISSUE TITLE
Blir mellanrum mellan innehållet och menylisten

### ISSUE THREAD

**Issue by me222wm** [rn222cx/1DV411_Grupp3#163]
![img_20160310_110628](https://cloud.githubusercontent.com/assets/8631192/13686521/68d3b4fc-e716-11e5-88f9-92c04c8e305a.jpg)

Gäller samtliga webbläsare på iPad.

**Comment by AndreasAnemyrLNU** [comment]
@me222wm är denna aktuell efter att @fh222dt publicerat igår?

**Comment by me222wm** [comment]
Tror inte att det är något man tänker på. Är ju likadant på de flesta siter.

**Comment by rn222cx** [comment]
Tror inte det heller. Du fick ansvaret för att stänga den om du ville i mötet.
