### ISSUE TITLE
Expert-view: om mycket text hamnar website under bilden. 

### ISSUE THREAD

**Issue by me222wm** [rn222cx/1DV411_Grupp3#164]
![img_0121](https://cloud.githubusercontent.com/assets/8631192/13687239/728e8dd8-e71a-11e5-9b8b-68668f0a26fe.PNG)

**Comment by rn222cx** [comment]
popup för info text

**Comment by rn222cx** [comment]
Ta bort centrerad rubrik

**Comment by AndreasAnemyrLNU** [comment]
Ska vara klart nu hoppas vi :)
