### ISSUE TITLE
Sidoscroll i chrome for Android

### ISSUE THREAD

**Issue by fh222dt** [rn222cx/1DV411_Grupp3#166]
Player-vyn går att scrolla i sidan, det är bara toppmenyn som är för bred. Detta uppstår ej i FF för Android. 

Testat på 2 olika enhter

**Comment by fh222dt** [comment]
Gäller även dashboard-vyn

**Comment by AndreasAnemyrLNU** [comment]
Är det fortfarande aktuellt efter att du mergat branch issue#148?

**Comment by me222wm** [comment]
Är fixat i mina enheter iaf.

**Comment by rn222cx** [comment]
fixat här med, nexus 5
