### ISSUE TITLE
Kommer inte åt log out i mobil (Endast Xperia)

### ISSUE THREAD

**Issue by fh222dt** [rn222cx/1DV411_Grupp3#167]
![20160311_084259](https://cloud.githubusercontent.com/assets/5398537/13696272/9dcb3780-e765-11e5-8e5d-8d563a7dd00b.jpg)

Det går inte att trycka på log out i chrome, men samma enhet i FF fungerar som det ska.

**Comment by mi222ep** [comment]
Får du den på alla vyer? För mig är det endast på playern och history när den är tom. På samtliga sidor går det även att scrolla ner under footern. På sidorna där det är mera innehåll uppstår inte problemet för mig.

**Comment by mi222ep** [comment]
Även profile settings.

**Comment by fh222dt** [comment]
Jag ser log out på tex dashboard & expert vy. Så det är nog som du säger, om sidans innehåll är för kort uppstår problemet. Men inte på alla mina enheter, fortfarande endast på Xperian, inte LGn

**Comment by mi222ep** [comment]
Felet ligger i att menyn skalar anpassat för liggande skärm. Ju högre skärmen är i förhållande till bredden, desto större blir felet.

**Comment by me222wm** [comment]
Ser bra ut på nexus och s4 mini efter uppdatering.

**Comment by rn222cx** [comment]
Ser bra ut på nexus 5
