### ISSUE TITLE
För lite utrymme runt explore-pop up

### ISSUE THREAD

**Issue by fh222dt** [rn222cx/1DV411_Grupp3#168]
Det blir väldigt trångt att kunna klicka utanför popupen för att stänga den i mobilen. I FF & chrome Android ligger popupen helt åt högerkanten.

**Comment by AndreasAnemyrLNU** [comment]
Frid hur bred kan popup vara tror du?

**Comment by AndreasAnemyrLNU** [comment]
Den har bredd 300px för tillfället och anpassades för ipone 4 som jag trodde var smal...

**Comment by fh222dt** [comment]
Om man bara ska ta hänsyn till att man ska klicka utanför så kanske 220? Men för att texter och checkboxarna ska få plats snyggt tror jag det blir för smalt. 

Det finns en del marginal till vänster om checkboxarna man kanske kan minska lite på

**Comment by AndreasAnemyrLNU** [comment]
Ligger åt höger fortfarande men betydligt smalare och minskad font-size dessutom

**Comment by fh222dt** [comment]
Har testat på min Xperia, och nu finns det plats för fingret att klicka utanför popupen!
