### ISSUE TITLE
Empty history

### ISSUE THREAD

**Issue by mi222ep** [rn222cx/1DV411_Grupp3#173]
När history är tom är det väldigt tomt. Ett litet meddelande "You have not yet listened to any podcasts" eller nåt vore trevligt.

**Comment by AndreasAnemyrLNU** [comment]
Klart!

**Comment by sj222mk** [comment]
Texten saknar marginal i iPhone6 stående!

**Comment by sj222mk** [comment]
![image1-1](https://cloud.githubusercontent.com/assets/5370740/13728115/49e3d510-e90d-11e5-9a80-b354e3eb98f7.PNG)

**Comment by AndreasAnemyrLNU** [comment]
Det är fixat!
