### ISSUE TITLE
Player "Back to expert link"

### ISSUE THREAD

**Issue by mi222ep** [rn222cx/1DV411_Grupp3#174]
Placeringen är lite konstig, tycker jag. Borde vara under spelaren istället. 
Kan vi formulera texten bättre? Det känns konstigt att gå "back to" expert när jag kommer direkt från slidern i dashboard.

**Comment by AndreasAnemyrLNU** [comment]
Osäker på grammatik men....

More by Dave Stein
More of Dave Stein

kanske kan vara ett alternativ gott nog?

**Comment by fh222dt** [comment]
Har flyttat länken så den ligger under expertens namn och döpt länken till "Visit profile page" är det ok? Eller ska den heta more by... Blir lite konstigt med namnet 2 gånger på samma ställe tyckte jag
