### ISSUE TITLE
History (podcast_user) behöver cascade på delete

### ISSUE THREAD

**Issue by sj222mk** [rn222cx/1DV411_Grupp3#175]

**Comment by AndreasAnemyrLNU** [comment]
@sj222mk  tänker du att om man raderar en user så raderas dess history i db?

**Comment by AndreasAnemyrLNU** [comment]
Skapat en branch issue#175

Har justerat sista migreringsfilen istället för ytterligare en för denna förändring.
Gjorde så för att vi ska slippa städa igen. Ok?

Frågan som återstår som @sj222mk påpekat:
Vilken data ska vara kvar eller raderas om en podcast raderas från panelen.
Jag tycker att har man lyssnat så har man lyssnat. Är podcasten in tillgänglig dödar man länken och kanske eventuellt gråmarkerar eller nåt?
