### ISSUE TITLE
http://utbildning.fridaholmstrom.se/password/reset

### ISSUE THREAD

**Issue by AndreasAnemyrLNU** [rn222cx/1DV411_Grupp3#202]
ingen marginal mot skärmens bredd
Iphone 4::Safari::FF::Chrome

**Comment by sj222mk** [comment]
Samma i iphone6

**Comment by sj222mk** [comment]
Samma på den sidan dit man kommer med mail-länk!

**Comment by rn222cx** [comment]
samma med nexus 5
