### ISSUE TITLE
Meny liggande  format

### ISSUE THREAD

**Issue by AndreasAnemyrLNU** [rn222cx/1DV411_Grupp3#208]
Övre menyval(Dashboard etc...) flyter ihop med undre menyval (profile settings etc...)
Påverkas vid scrollning av sida

Iphone 4
Meny ::: Chrome :: FF :: Safari

**Comment by fh222dt** [comment]
Så blir det i min xperia med (liggande). Men endast när webbläsarens adressfält är synligt vilket det bara är innan man scrollat nåt. Första intrycket är inte så snyggt

**Comment by ehamrin** [comment]
Åtgärdat i https://github.com/rn222cx/1DV411_Grupp3/commit/30d5b78dc0efe9704f48bab293e36fa764bca568

Jag har inte satt upp Vagrant-delningen, kan någon av er som har problemet testa med den och se att det är löst i branchen issue#208?

**Comment by AndreasAnemyrLNU** [comment]
Yes strax då...

**Comment by AndreasAnemyrLNU** [comment]
Ni som har problem med liggande format gällande meny….

Test @ehamrin fix på följande:

http://quick-deer-4816.vagrantshare.com

**Comment by AndreasAnemyrLNU** [comment]
Iphone 4 fungerar ej ännu...

**Comment by fh222dt** [comment]
Fungerar på min enhet

**Comment by AndreasAnemyrLNU** [comment]
@channel

Kontroller liggande enheter så att menyn fungerar nu….

OBS! ny url för delning...

http://entertaining-wolf-3939.vagrantshare.com

**Comment by fh222dt** [comment]
fungerar!

**Comment by ehamrin** [comment]
Åtgärdat i https://github.com/rn222cx/1DV411_Grupp3/pull/213
