### ISSUE TITLE
Reset password felmeddelande

### ISSUE THREAD

**Issue by mi222ep** [rn222cx/1DV411_Grupp3#211]
När jag försöker återställa lösenordet andra gången med samma länk får jag felmeddelande:
"This password reset token is invalid."
Det är en ganska nördigt svar. Nåt i stil med "This link has already been used. Request a new reset link {Länk}" eller nåt är nog lättare att förstå för vanliga användare. Vad tycker ni?

**Comment by ehamrin** [comment]
Fast "This password reset token is invalid." kan betyda två saker:

1. Den är redan använd
2. Någon har försökt att mata in en egen som inte är registrerad

"This link has already been used. Request.."  pekar bara på punkt nummer 1.

**Comment by AndreasAnemyrLNU** [comment]
Antar att det meddelandet även gälle tidsbunden länk. Tror att jag sett att länk gäller ca 60min ?

**Comment by AndreasAnemyrLNU** [comment]
Föreslår att vi inte petar i det idag?

**Comment by mi222ep** [comment]
Jag tänker t.ex min mamma, hon hade inte förstått vad det innebar att en token var ogiltig. Särskilt som felmeddelandet kommer först efter att formuläret har skickats. Hon hade mycket väl kunnat tro att det var någon konstig validering och försöka mata in nya lösenord.
"This link has expired" eller liknande funkar också och är mer öppet. Men det är inget jag tänker slåss för om gruppen är överens om att "token invalid" är bättre.

**Comment by sj222mk** [comment]
Tyvärr håller jag med Matilda. Om detta inte är för avancerat bör det fixas innan slutleverans! Detta meddelande är självklart när man jobbar med datorer/kod men knappast för alla i målgruppen!

**Comment by ehamrin** [comment]
Det finns i denna filen om man vill ändra det: https://github.com/rn222cx/1DV411_Grupp3/blob/master/sales-scenario/resources/lang/en/passwords.php#L19
